Update rust.yml

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -15,13 +15,31 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
-    - name: Install dependencies
+    - name: Install Dependencies
       run: |
-        sudo apt-get update
-        sudo apt-get install -y --no-install-recommends \
-          libgtk-3-dev \
-          libpango1.0-dev
-    - name: Build
-      run: cd napture && cargo build --verbose
-    - name: Run tests
-      run: cd napture && cargo test --verbose
+          echo "Installing dependencies..."
+          if [ -f /etc/os-release ]; then
+              PRETTY_NAME=$(grep '^PRETTY_NAME=' /etc/os-release | cut -d '=' -f2- | tr -d '"')
+              if [ "$PRETTY_NAME" == "Ubuntu 24.04 LTS" ]; then
+                  echo "Detected $PRETTY_NAME and installing dependencies..."
+                  sudo apt-get update
+                  sudo apt-get install -y curl git build-essential libssl-dev libglib2.0-dev libcairo2-dev libgraphene-1.0-dev libgtk-4-dev libadwaita-1-dev liblua5.4-dev
+                  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
+                  echo "Dependencies installed."
+              else
+                  echo "Could not detect the Linux distribution and version. Now continuing with build, without attempting to install dependencies."
+              fi
+          else
+              echo "Could not detect the Linux distribution and version. Now continuing with build, without attempting to install dependencies."
+          fi
+
+    - name: Update Repository
+      run: |
+          echo "Updating repository..."
+          git pull origin $(git rev-parse --abbrev-ref HEAD)
+
+    - name: Build Napture
+      run: |
+          echo "Building Napture..."
+          cd napture || exit 1
+          cargo build --verbose
