Update rust.yml

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -60,6 +60,52 @@ jobs:
         path: napture-v${{ github.sha }}.AppImage
       env:
         UPLOAD_URL: ${{ steps.upload.outputs.upload_url }}  
+  build_macos:
+    name: Build Napture (MacOS)
+    runs-on: macos-latest
+
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install deps
+        run: |
+          brew install gtk4 graphene glib libadwaita lua create-dmg pkg-config
+          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+          arch -x86_64 /usr/local/bin/brew install gtk4 graphene glib libadwaita lua pkg-config || exit 0 # Brew tries to link python which will fail
+      - name: Build Napture
+        run: |
+          rustup target add x86_64-apple-darwin
+          cd napture
+          RUSTFLAGS='-L /opt/homebrew/Cellar/' cargo build --release --target aarch64-apple-darwin
+          PKG_CONFIG='/usr/local/bin/pkg-config' RUSTFLAGS='-L /usr/local/Cellar/' cargo build --release --target x86_64-apple-darwin
+          lipo -create target/aarch64-apple-darwin/release/webx target/x86_64-apple-darwin/release/webx -output target/release/webx
+      - name: Make an app bundle
+        run: |
+          cd napture
+          mkdir -p target/release/Napture.app/Contents/MacOS
+          cp target/release/webx target/release/Napture.app/Contents/MacOS
+          cp ./Info.plist target/release/Napture.app/Contents
+          mkdir -p target/release/Napture.app/Contents/Resources/AppIcon.iconset
+
+          for SIZE in 16 32 64 128 256 512; do
+              sips -z $SIZE $SIZE ./file.png --out target/release/Napture.app/Contents/Resources/AppIcon.iconset/icon_${SIZE}x${SIZE}.png
+          done
+          for SIZE in 32 64 256 512; do
+              sips -z $SIZE $SIZE ./file.png --out target/release/Napture.app/Contents/Resources/AppIcon.iconset/icon_$(expr $SIZE / 2)x$(expr $SIZE / 2)x2.png
+          done
+
+          iconutil -c icns -o target/release/Napture.app/Contents/Resources/AppIcon.icns target/release/Napture.app/Contents/Resources/AppIcon.iconset
+          rm -rf target/release/Napture.app/Contents/Resources/AppIcon.iconset
+      - name: Sign the app
+        run: codesign --force --deep --sign - napture/target/release/Napture.app
+      - name: Pack Napture into DMG
+        run: |
+          cd napture/target/release
+          create-dmg Napture-macos-universial.dmg Napture.app
+      - name: Upload DMG Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: napture-v${{ github.sha }}.dmg
+          path: napture/target/release/Napture-macos-universial.dmg
         
   build_win:
     name: Build Napture (Windows)
@@ -71,7 +117,6 @@ jobs:
     - name: Install Dependencies
       run: |
         echo "Installing dependencies..."
-        choco install -y gtk-runtime
         rustup toolchain install stable-gnu && rustup default stable-gnu
         echo "Dependencies installed."
 
@@ -82,28 +127,15 @@ jobs:
         install-dir: 'C:\msys64'
     
     - name: Install MSYS2 dependencies
-      shell: msys2 {0}
       run: |
         echo "Installing MSYS2 packages..."
-        pacman --noconfirm -S mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-gtk4 mingw-w64-x86_64-gettext mingw-w64-x86_64-libxml2 mingw-w64-x86_64-librsvg mingw-w64-x86_64-pkgconf mingw-w64-x86_64-gcc mingw-w64-x86_64-libadwaita mingw-w64-x86_64-lua mingw-w64-x86_64-pkg-config
-
-    - name: Set PATH
-      run: |
-        echo "Setting PATH..."
-        $Env:Path += ';C:\msys64\mingw64\include;C:\msys64\mingw64\bin;C:\msys64\mingw64\lib'
-
-    - name: Verify pkg-config
-      shell: powershell
-      run: |
-        echo "Verifying pkg-config installation..."
-        which pkg-config
-        pkg-config --version
+        C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
+        C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-gtk4 mingw-w64-x86_64-gettext mingw-w64-x86_64-libxml2 mingw-w64-x86_64-librsvg mingw-w64-x86_64-pkgconf mingw-w64-x86_64-gcc mingw-w64-x86_64-libadwaita mingw-w64-x86_64-lua"
 
     - name: Build Napture
       run: |
         echo "Building Napture..."
         $Env:Path += ';C:\msys64\mingw64\include;C:\msys64\mingw64\bin;C:\msys64\mingw64\lib'
-        pkg-config --help
         cd napture
         cargo build --release --verbose
         echo "Napture built successfully."
@@ -122,6 +154,7 @@ jobs:
    needs:
       - build
       - build_win
+      - build_macos
    steps:
       - name: Download Ubuntu Artifact
         uses: actions/download-artifact@v4.1.7
@@ -132,6 +165,10 @@ jobs:
         uses: actions/download-artifact@v2
         with:
           name: napture-v${{ github.sha }}.exe
+      - name: Download MacOS Artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: napture-v${{ github.sha }}.dmg    
       - name: Download Dependencies
         run: |
             sudo add-apt-repository universe
@@ -145,4 +182,5 @@ jobs:
           files: |
             napture-v${{ github.sha }}.AppImage
             napture-v${{ github.sha }}.exe
+            napture-v${{ github.sha }}.dmg
           prerelease: true
